<?php
declare(strict_types=1);

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class InstallingRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'email' => 'required|email|max:128',
            'password' => 'required|min:6|max:32',
            'title' => 'required|max:255',
            'subtitle' => '',
            'nickname' => '',
        ];
    }

    protected function failedValidation(Validator $validator)
    {
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public function messages()
    {
        return [
            'email.required' => "邮箱地址不能为空",
            'email.max' => "邮箱地址超出最大长度",
            'password.required' => "密码不能为空",
            'password.min' => "密码不能小于6位",
            'password.max' => "密码不能大于32位",
            'title.required' => "站点名称不能为空",
            'title.max' => "站点名称太长了",
        ];
    }
}
