<?php

namespace App\Exceptions;

use App\Http\Result;
use Exception;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Http\Response;
use Illuminate\Validation\ValidationException;
use Symfony\Component\HttpKernel\Exception\HttpExceptionInterface;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {
        if (config('app.debug')) {
            return parent::render($request, $e);
        }
        $viewExist = true;
        try {
            app('view');
        } catch (Exception $_) {
            $viewExist = false;
        }
        $storagePath = storage_path();
        if ($viewExist && stripos($e->getMessage(), $storagePath) === false) {
            // TODO: Change the autogenerated stub
            return parent::render($request, $e);
        } else {
            return new Response($this->renderFatal([
                'css' => mix("/assets/css/app.css"),
                'exception' => $e,
                'message' => $e->getMessage(),
            ]), 500);
        }
    }

    /**
     * @param array $arguments
     * @param string $theme
     * @return false|string
     */
    protected function renderFatal(array $arguments = [], string $theme = 'default')
    {
        extract($arguments);
        ob_start();
        include resource_path("views/themes/{$theme}/errors/fatal.blade.php");
        return ob_get_clean();
    }

    protected function registerErrorViewPaths()
    {

    }

    protected function getHttpExceptionView(HttpExceptionInterface $e)
    {
        return "default.errors.{$e->getStatusCode()}";
    }

    /**
     * Convert a validation exception into a JSON response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Validation\ValidationException  $exception
     * @return \Illuminate\Http\JsonResponse
     */
    protected function invalidJson($request, ValidationException $exception)
    {
        return response()->json(
            Result::err(
                $exception->status,
                $exception->getMessage(),
                $exception->errors(),
            ), $exception->status);
    }
}
